### ISSUE TITLE
Adapter activities yaml having embedded json - formatting issues

### ISSUE THREAD

**Issue by jeffbanks** [nosqlbench/nosqlbench#1132]
**Describe the bug**
Adapter activities in YAML w/ embedded json are not retaining the proper formatting for valid yaml processing.  This causes the scenario's activity to fail without much detail regarding root cause.  This appears to occur upon commit (of valid yaml) to github for the scenario scripts.

Example of bad yaml formatting as the YAML processor is expecting consistent space alignment:

```yaml
body: |
          {
            "name": "<<table:keyvalue>>",
            "columnDefinitions": [
                {
                    "name": "key",
                    "typeDefinition": "text"
                },
       ...
```

Expected
```yaml
body: |
          {
            "name": "<<table:keyvalue>>",
            "columnDefinitions": [
              {
                "name": "key",
                "typeDefinition": "text"
              },
       ...
```
