### ISSUE TITLE
Extend workload template to support sub-op templates in a more uniform way

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1147]
In order to allow for compound operations, known as batch statements in CQL and under other names in other protocols, the workload template format needs to be extended.

This will allow for the separate scenarios single operations and compound operations to be expressed distinctly, checked for structural coherence, and mapped directly to the correct mapper interface.

The current supported data structures only recognize "op" as a specific field within the ParsedOp. This needs to be extended to support multiple ops.

Example syntax:
```yaml
blocks:
 block1:
  ops:
   op1:
    sharedfield: "{shared}"
    bindings:
     shared: NumberNameToString();
    ops:
     part1: "asdf"
     part2: "zxcv"
```

In this case, an additional occurence of "ops" is allowed _under_ the op template. This should be desugared to the equivalent:
```yaml
blocks:
 block1:
  ops:
   op1:
    sharedfield: "{shared}"
    bindings:
     shared: NumberNameToString();
    op:
     ops:
      part1: "asdf"
      part2: "zxcv"
```
... the differnce being that the second form adheres to the extant requirements that all op fields are located underneath "op" or "params" when specified, but that all other op template level fields are either reserved words or unreserved words which are automatically moved into one of these properties.

In both cases, it is implied that the op template level bindings, tags, params and so on are cascaded to each of the interior op templates just as they would be at higher levels in the doc.
