### ISSUE TITLE
http-rest-timeseries: baseline/activities - Failing in NB5

### ISSUE THREAD

**Issue by jeffbanks** [nosqlbench/nosqlbench#1148]
**Describe the bug**
Unable to get a successful execution of this specific scenario `adapter-http/activities/baseline/http-rest-timeseries`.  This is run on Ubuntu 

Local Stargate Docker instances running are reporting error code `400` without further detail other than:
```
5097 ERROR [httpresttimeseries_default_schema:001] CoreMotor    Error in core motor loop:java.lang.RuntimeException: java.lang.RuntimeException: io.nosqlbench.adapter.http.errors.InvalidStatusCodeException: Server returned status code '400' which did not match ok_status '2..'
java.lang.RuntimeException: java.lang.RuntimeException: io.nosqlbench.adapter.http.errors.InvalidStatusCodeException: Server returned status code '400' which did not match ok_status '2..'
```

CLI:
```
./nb5/target/nb5 adapter-http/src/main/resources/activities/baselines/http-rest-timeseries.yaml default restapi_host=localhost
```

**What was Expected**
Since similar configurations exist with `http-rest-keyvalue` and `http-rest-tabular` expecting this scenario to execute successfully.

**Additional context**
```yaml
min_version: "5.17.1"

description: |
  This workload emulates a time-series data model and access patterns.
  This should be identical to the cql variant except for:
  - We can't specify the write timestamp to make the write idempotent like we can with cql.
  - The `time` binding has to have a StringDateWrapper to get the exact format that the REST API needs; See https://github.com/stargate/stargate/issues/532.
  - We need to URLEncode the `data` binding because newlines can't be sent in REST calls.
  - Schema creation is cql of the lack of being able to define compaction strategy in the REST API.
  - There is no instrumentation with the http driver.
  - There is no async mode with the http driver.
  - Refer to 'http-rest.md' for more information.

scenarios:
  default:
    schema: run driver=http tags==block:"schema.*" threads==1 cycles==UNDEF
    rampup: run driver=http tags==block:"rampup.*" cycles===TEMPLATE(rampup-cycles,1) threads=auto
    main: run driver=http tags==block:"main.*" cycles===TEMPLATE(main-cycles,10) threads=auto

bindings:
  weighted_hosts: WeightedStrings('<<restapi_host:stargate>>')
  request_id: ToHashedUUID(); ToString();
  auto_gen_token: Discard(); StargateToken('http://localhost:8081/v1/auth'); ToString();

  machine_id: Mod(<<sources:10000>>); ToHashedUUID() -> java.util.UUID
  sensor_name: HashedLineToString('data/variable_words.txt');
  time: Mul(<<timespeed:100>>L); Div(<<sources:10000>>L); StringDateWrapper("yyyy-MM-dd'T'hh:mm:ss'Z");
  sensor_value: Normal(0.0,5.0); Add(100.0) -> double
  station_id: Div(<<sources:10000>>);Mod(<<stations:100>>); ToHashedUUID() -> java.util.UUID
  data: HashedFileExtractToString('data/lorem_ipsum_full.txt',800,1200); URLEncode();

blocks:
  rampup:
    ops:
      rampup-insert:
        method: POST
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/keyspaces/<<keyspace:baselines>>/<<table:iot>>
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"
        body: |
          {
            "machine_id": "{machine_id}",
            "sensor_name": "{sensor_name}",
            "time": "{time}",
            "sensor_value": "{sensor_value}",
            "station_id": "{station_id}",
            "data": "{data}"
          }
  schema:
    ops:
      create-keyspace:
        method: POST
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/schemas/keyspaces
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"
        body: |-
          {
            "name": "<<keyspace:baselines>>",
            "replicas": <<rf:1>>
          }

      drop-table:
        method: DELETE
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/schemas/keyspaces/<<keyspace:baselines>>/tables/<<table:iot>>
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"
        ok-status: "[2-4][0-9][0-9]"

      create-table:
        method: POST
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/schemas/keyspaces/<<keyspace:baselines>>/tables
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"
        body: |-
          {
            "name": "<<table:iot>>",
            "columnDefinitions": |-
              [
                {
                  "name": "machine_id",
                  "typeDefinition": "uuid"
                },
                {
                  "name": "sensor_name",
                  "typeDefinition": "text"
                },
                {
                  "name": "time",
                  "typeDefinition": "timestamp"
                },
                {
                  "name": "sensor_value",
                  "typeDefinition": "double"
                },
                {
                  "name": "station_id",
                  "typeDefinition": "uuid"
                },
                {
                  "name": "data",
                  "typeDefinition": "text"
                }
              ],
            "primaryKey": |-
            {
              "partitionKey": |-
                [
                  "machine_id",
                  "sensor_name"
                ],
              "clusteringKey": |-
                [
                  "time"
                ]
            },
            "tableOptions": |-
            {
              "clusteringExpression": |-
                [
                  {
                    "column": "time",
                    "order": "DESC"
                  }
                ]
            },
            "ifNotExists": true
          }

  main-read:
    params:
      ratio: <<read_ratio:1>>
    ops:
      main-select:
        method: GET
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/keyspaces/<<keyspace:baselines>>/<<table:iot>>?where=URLENCODE[[{"machine_id":{"$eq":"{machine_id}"},"sensor_name":{"$eq":"{sensor_name}"}}]]&page-size=<<limit:10>>
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"

  main-write:
    params:
      ratio: <<write_ratio:9>>
    ops:
      main-write:
        method: POST
        uri: <<protocol:http>>://{weighted_hosts}:<<restapi_port:8082>><<path_prefix:>>/v2/keyspaces/<<keyspace:baselines>>/<<table:iot>>
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:{auto_gen_token}>>"
        Content-Type: "application/json"
        body: |-
          {
            "machine_id": "{machine_id}",
            "sensor_name": "{sensor_name}",
            "time": "{time}",
            "sensor_value": "{sensor_value}",
            "station_id": "{station_id}",
            "data": "{data}"
          }
```
