### ISSUE TITLE
Parameters not propagated to the op

### ISSUE THREAD

**Issue by ivansenic** [nosqlbench/nosqlbench#1182]
**Describe the bug**
As suggested to @jshook, I tried to use the following to define space in all operations:

```
bindings:
  space: HashRange(1,<<connections:20>>); ToString();

params:
  space: >-
    {space}

blocks:
  schema:
    ops:
      my-op:
```

However, this is not working and space needs to be defined explicitly:

```

blocks:
  schema:
    ops:
      my-op:
        space: "{space}"
```

**To Reproduce**
Setup the workflow yaml as above.

**What was Expected**
Space parameter does not have to be defined in every op explicitly.
