### ISSUE TITLE
Explicit operation name not included in the tags

### ISSUE THREAD

**Issue by ivansenic** [nosqlbench/nosqlbench#1247]
**Describe the bug**

Having a block like this:

```
blocks:
  main: 
   ops:
     operation1:
        name: some_name
        ....

     operation2:
        name: another_name
        ....
```

Does not define the runtime tags `name=some_name` and `name=another_name`.. Names for operations are still constructed in some way that I have hard time predicting, although I read this document: https://docs.nosqlbench.io/workloads-101/10-stmt-naming/

The run executions that contain `nb5 .. tags=name:some_name` complains with:

> There were no active op templates with tag filter 'name:some_name', since all 14 were filtered out.

**To Reproduce**
Use version `5.17.3-release` and create a scenario like above.

**What was Expected**
When operation defines explicit name, that such name is set as tag.
