### ISSUE TITLE
Allow easy JSON templating without indirection through structural template

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1376]
Sometimes we want to be able to provide a payload to an HTTP or similar request. There are multiple ways a user may want to express this. A typical form is as a string template with the JSON structure written out long-form:

```yaml
bindings:
 number: NumberNameToString()
ops:
 op1:
  payload: |
   { "id": "{number}", "color", "blue" }
```

However, there are many cases where a user would rather do something that is syntax checked within YAML as a template directly. A structural version of the above would look like this:

```yaml
bindings:
 number: NumberNameToString()
ops:
 op1:
  id: "{number}"
  color: blue
```

This is not only easier to read, even for smaller structures, but it avoids encoding one format inside another in a way that makes it difficult to verify and understand. The more interesting the structure, the more benefit the user will get from using the simpler form.

The first form is already possible, and the second form is already possible, but there is a catch: When using the second form, for each cycle:
1. First, the structural template has to be rendered into a Java object or structure first
2. Second, it must be passed to a low-level driver interface that understands how to use the structure.

This is simply inefficient and limited. While the syntax of the second form is desirable, the implementation for how it is rendered to a payload body is not.

## Improvement

A user should be able to use the second form as a template for a textual payload body. In order to do this, we need to be able to interpret the template as JSON in raw form firsst, and then interpret the result of that as a string template.

It should be somewhat easy to do this, given that the embedded binding references will (should) be in the form {word} or {{word}}, which are not distinctively valid JSON or YAML. Once the template structure is rendered to JSON, what remains should be a valid textual template like the first example: `{ "id": "{number}", "color", "blue" }`. This now constitutes the same type of string template from the very first example above. Only, the user didn't have to write this directly and instead was allowed to use a simpler and more robust representation of the op template.

## Distinction

Given that there can be some ambiguity for users about what is happening with the op template, we'll need to have a way to specify one format or another and to make it clear exactly when to use either. There are cases for which a field should always be rendered into the template object and used as such. There are other cases where an op field (Or the whole op as a collection of op fields) represents wholly and directly what should be the payload of an operation, not as a structure or object, but as a request body.

**Comment by dave2wave** [comment]
The following format might be more natural and fall into a natural convert the yaml dict into a json dict natural syntax.

```yaml
bindings:
 number: NumberNameToString()
ops:
 op1:
  payload:
   id: "{number}"
   color: blue
```

**Comment by dave2wave** [comment]
We need to somehow know that `payload` json may need to be created while creating the op component. Once we understand that this should be relatively easy to synthesize the `payload`

```
bindings:
 number: NumberNameToString()
ops:
 op1:
  payload: json
  id: "{number}"
  color: blue
```

Having a `json` as the value would trigger a json template built from all the other structure at that level of the yaml.
