### ISSUE TITLE
Reading boolean statement from yaml causes casting error

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#168]
With 
```
 statements:
  - ...
    params:
     prepared: true
```
the latest cql driver fails on init

[update] This only happens for params directlly tied to statements in "free param" format.
