### ISSUE TITLE
Error Pulling HDF5 file from S3 using `HdfFileToFloatList`

### ISSUE THREAD

**Issue by MikeYaacoubStax** [nosqlbench/nosqlbench#1957]
**Description**
Passing in a public URL for an HDF5 file to `HdfFileToFloatList` causes the following error:
`ERROR [main] ERRORHANDLER Error from driver or included library: io.jhdf.exceptions.HdfException: Failed to open file '/vector/ANN/intfloat_e5_small_v2_100KV_10KQ/intfloat_e5-small-v2_100000.hdf5' . Is it a HDF5 file?`

**To Reproduce**

- *Prerequisites*
  - You will need an Astra DB to target, with its secure connect bundle and credentials (user/pass/token).
  - You will need to be able to run NB5 through docker.
  - You will need to download the vector workload attached to this issue as a reference at the end. (astra-vector-live-simplified.yaml)
  - You will need to modify the file to input the url of a public hdf5 file that can be curl downloaded.
 
- *Docker Run*
Assuming all of the prerequisite files are in your working directory:
```bash
docker run -it --rm \
    -v "$(pwd)":/workdir \
    nosqlbench/nosqlbench:5.21.1-preview \
    /workdir/astra-live-vector-simplified.yaml setup \
    cyclerate=20 \
    scb=/workdir/<scb_file_name>.zip \
    userfile=/workdir/usernamefile \
    passfile=/workdir/passwordfile \
    keyspace=<keyspace in your astra DB> \
    errors=counter \
    -vv > nosqlbench_output.log 2>&1
```

You should see the above error message in the output log.

**Additional context**
- Passing in the hdf5 file locally works.
- This is reproduced on Linux, with NB5's latest preview release 5.21.1-preview

**Workload reference**
```yaml
scenarios:
  setup:
    drop: run tags='block:drop' labels='target:astra' threads===1 cycles===2
    schema: run tags='block:schema' labels='target:astra' threads===1 cycles===2
    rampup: run tags='block:rampup' labels='target:astra' threads=100 cycles=TEMPLATE(trainsize) errors=counter
  search:
    search_and_index: >-
      run alias=search_and_index tags='block:search_and_index,optype=select' labels='target:astra'
      cycles=3B errors=count,retry stride=100 striderate=17.5 threads=auto
params:
  driver: cqld4
  instrument: true

bindings:
  id: ToString()
  # This
  test_floatlist: HdfFileToFloatList("<S3 URL FOR HDF5 FILE>", "/test"); ToCqlVector();
  relevant_indices: HdfFileToIntArray("<S3 URL FOR HDF5 FILE>", "/neighbors")
  distance_floatlist: HdfFileToFloatList("<S3 URL FOR HDF5 FILE>", "/distance")
  train_floatlist: HdfFileToFloatList("<S3 URL FOR HDF5 FILE>", "/train"); ToCqlVector();

blocks:
  drop:
    params:
      cl: TEMPLATE(cl,LOCAL_QUORUM)
      prepared: false
      timeout: 10.0
    ops:
      drop_index: |
        DROP INDEX IF EXISTS TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors);
      drop_table: |
        DROP TABLE IF EXISTS TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors);
  schema:
    params:
      cl: TEMPLATE(cl,LOCAL_QUORUM)
      prepared: false
      timeout: 10.0
    ops:
      create_table: |
        CREATE TABLE IF NOT EXISTS TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors) (
          key TEXT,
          value vector<float,384>,
          PRIMARY KEY (key)
        );
      create_sai_index: |
        CREATE CUSTOM INDEX IF NOT EXISTS ON TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors) (value) USING 'StorageAttachedIndex'
        WITH OPTIONS = {'similarity_function' : 'TEMPLATE(similarity_function,cosine)'};

  rampup:
    params:
      cl: TEMPLATE(write_cl,LOCAL_QUORUM)
      prepared: true
      timeout: 10.0
    ops:
      insert: |
        INSERT INTO TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors)
        (key, value) VALUES ({id},{train_floatlist});
  search_and_index:
    ops:
      select_ann_limit:
        prepared: |
          SELECT * FROM TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors)
          ORDER BY value ANN OF {test_floatlist} LIMIT TEMPLATE(select_limit,100);
        tags:
          optype: select
        verifier-init: |
          relevancy=scriptingmetrics.newRelevancyMeasures(_parsed_op,"group","relevancy");
          for (int k in List.of(100)) {
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.recall("recall",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.precision("precision",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.F1("F1",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.reciprocal_rank("RR",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.average_precision("AP",k));
          }
          for (int k in List.of(1,2,3,5,10,25,50,75)) {
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.recall("s_recall",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.precision("s_precision",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.F1("s_F1",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.reciprocal_rank("s_RR",k));
            relevancy.addFunction(io.nosqlbench.engine.extensions.computefunctions.RelevancyFunctions.average_precision("s_AP",k));
          }
        verifier: |
          // driver-specific function
          actual_indices=cql_utils.cqlStringColumnToIntArray("key",result);
          // driver-agnostic function
          relevancy.accept({relevant_indices},actual_indices);
          // because we are "verifying" although this needs to be reorganized
          return true;
      insert_rewrite:
        prepared: |
          INSERT INTO TEMPLATE(keyspace,baselines).TEMPLATE(table,vectors)
          (key, value) VALUES ({id},{train_floatlist});
        tags:
          optype: insert
```
