### ISSUE TITLE
Pull Requests Run the Build Workflow Twice

### ISSUE THREAD

**Issue by dave2wave** [nosqlbench/nosqlbench#1981]
**Describe the bug**

In `.github/workflows/build.yml` the `on` condition causes the workflow to run twice

```yaml
on:
  push:
    # tags:
      # - "![0-9]+.[0-9]+.[0-9]+-preview"
      # - "![0-9]+.[0-9]+.[0-9]+-release"
  pull_request:
```

**To Reproduce**
1. Create a PR.
2. Push changes.

**What was Expected**
The build and buidldocs job steps should appear once and not twice

**Additional context**
We should discuss, but the workflow should have either the `push` or the `pull_request` conditions, and not both.
