### ISSUE TITLE
Sequence Number Always Stays 1 in Workload for NoSQLBench Pulsar Adapter

### ISSUE THREAD

**Issue by shivamtomard11** [nosqlbench/nosqlbench#2011]
**Describe the bug**
The sequence number always stays at 1 in the produced message for the NoSQLBench Pulsar adapter.

**To Reproduce**
1. Create the following workload YAML:
`params:
  seq_tracking: 'true'

bindings:
  mykey: NumberNameToString()
  mypropval: AlphaNumericString(5)
  myvalue: AlphaNumericString(20)

blocks:
  msg_pub:
    ops:
      op1:
        MessageProduce: "persistent://public/default/pub1"
        msg_key: "{mykey}"
        msg_prop: |
          {
            "prop1": "{mypropval}"
          }
        msg_value: "{myvalue}"`
        
2.	Run the load using the following commands (try both the jar and binary):
`sudo ./nb5 run driver=pulsar cycles=1000 threads=auto web_url=http://host:8080 service_url=pulsar://host:6650 config=config.properties workload=./load_file.yaml cyclerate=10 --progress console:1s --report-prompush-to http://host:8428/api/v1/import/prometheus/metrics/job/myjob/instance/myinstance_noseq_track --add-labels jobname=myjob,instance=myinstance_noseq_track

sudo java --enable-preview -jar nb5.jar run driver=pulsar cycles=1000 threads=auto web_url=http://host:8080 service_url=pulsar://host:6650 config=config.properties workload=./load_file.yaml cyclerate=10 --progress console:1s --report-prompush-to http://host:8428/api/v1/import/prometheus/metrics/job/myjob/instance/myinstance_noseq_track --add-labels jobname=myjob,instance=myinstance_noseq_track`

3.	Observe the output messages, using any pulsar consumer client.
Here are the output messages:

`publishTime:[1722894916402], eventTime:[0], key:[eleven], properties:[prop1=38WPT, sequence_number=1], content:38WPTLYKCVLOEGNX1J34
----- got message -----
publishTime:[1722894916402], eventTime:[0], key:[nine], properties:[prop1=K5AI1, sequence_number=1], content:K5AI14NVGZQ9EWHHK5YT
----- got message -----
publishTime:[1722894916402], eventTime:[0], key:[ten], properties:[prop1=H6G9X, sequence_number=1], content:H6G9XA56KSTNSTJWPORX
----- got message -----
publishTime:[1722894916416], eventTime:[0], key:[twelve], properties:[sequence_number=1, prop1=13UFE], content:13UFEF2YOMSJAQOB5WM4
----- got message -----
publishTime:[1722894916517], eventTime:[0], key:[thirteen], properties:[sequence_number=1, prop1=4ZYNM], content:4ZYNM05XLN5I2TXPUZIB
----- got message -----
publishTime:[1722894916618], eventTime:[0], key:[fourteen], properties:[sequence_number=1, prop1=F8GNQ], content:F8GNQ8V0OIGNQWDEI3JD
----- got message -----
publishTime:[1722894916718], eventTime:[0], key:[fifteen], properties:[sequence_number=1, prop1=EE056], content:EE056F22FV97IJ0901DG
----- got message -----
publishTime:[1722894916819], eventTime:[0], key:[sixteen], properties:[sequence_number=1, prop1=AE0ZX], content:AE0ZX45C1WVKQQS9SFBM
----- got message -----
publishTime:[1722894916920], eventTime:[0], key:[seventeen], properties:[sequence_number=1, prop1=KDQK2], content:KDQK2YOHPXY4QFVIXQMO
----- got message -----
publishTime:[1722894917021], eventTime:[0], key:[eighteen], properties:[sequence_number=1, prop1=O10AF], content:O10AFSI6OEIM4QHAU55S
----- got message -----
publishTime:[1722894917122], eventTime:[0], key:[nineteen], properties:[sequence_number=1, prop1=7D3PT], content:7D3PT81T0NAX511B6P5W
----- got message -----`

**What was Expected**
The sequence number should increment with each message produced.

**Additional context**
OS:  CentOS Linux release 7.9.2009 (Core)
environment:  Normal java process
version info : 5.21.2-release

**Screenshots, if applicable**

**Comment by dave2wave** [comment]
Maybe try a variation of bindings like these:

```yaml
bindings:
  seq_key: Mod(TEMPLATE(keycount,1000000000)); ToString() -> String
  seq_value: Hash(); Mod(TEMPLATE(valuecount,1000000000)); ToString() -> String
  batch_seq_value: Mul(TEMPLATE(batchsize,100)L); Hash(); Mod(TEMPLATE(valuecount,1000000000)); ToString() -> String
  rw_key: TEMPLATE(keydist,Uniform(0,1000000000)); ToString() -> String
  rw_value: Hash(); TEMPLATE(valdist,Uniform(0,1000000000)); ToString() -> String
```

Change the names as necessary.
