### ISSUE TITLE
make bindings format more flexible in YAML

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#212]
Presently, bindings properties in YAML files are treated as simply a map under the name `bindings`, regardless of where it occurs (document root, block, or statement). Improvements to the bindings system will require more flexiblity in structure.

The more flexible data structure should support the existing form without change to behavior.
Additionally, it should support:
- Description of a binding recipe
- Examples of the binding recipe
- Name parameter fields from the runtime environment.

A proposed structure looks like this:
```yaml
bindings:
 - b1: NormalBinding1()
 - b2:
    spec: NestedBindingA(initializer1=523)
    desc: This is the nested binding `NestedBindingA()`
    example: NestedBindingA(initializer1=100)
    params:
      p1: val1
      p2: val2
  - name: Example3
    spec: NestedBindingB(init='234')
    description: This is the description
    p3: val3
---
bindings:
 b1: NormalBinding1()
 b2:
   specifier: ... and so on
```

Notable features of this example:
* For the bindings property, both list and map forms are supported. If the root form is a map, then the keys are taken to be the names under which the bindings are defined.
* Within the list form, the same rules apply as with the map form, although the list form can't guarantee uniqueness in keys. This will be enforced by the mapping logic as an error if it occurs.
* Whenever the essential map element contains a single string value, regardless of the surrounding structure (list or map), this is interpreted as current bindings are, no changes.
* map of one string key and value: One-entry maps are supported, and as with the statement forms, are assumed to be a (name, spec) tuple.
* both desc and description are supported as synonyms, as well as spec and specifier
* reserved words are name,,desc,description,spec,specifier, and params. In compound map forms, any word which is not a reserved word is pushed down into the parameters structure automatically on parsing.

The point of these conventions are to:
1. aAlow common expectations of reasonably descriptive structure to just work.
2. Only require the minimum absolutely necessary to work in the simplest case
3. Allow designers to add details as needed with their selected level of terseness
4. Adhere to some of the conventions established in the yaml form for op templates, which has had enough user testing that is is a known quantity. It's still a structured markup language, but it seems to work for a variety of workflow styles.
