### ISSUE TITLE
docker build should be via in-repo script first

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#2140]
When building the docker image, it should be very easy to emulate what happens during official builds, without the docker hub interaction. Since the parameters for this are somewhat embedded in the github action, these and the upstream version extraction should be pulled down into a scripts/build-docker.sh or similar.  Then, the github action can simple invoke this script so that devs and users are able to experiment and build their own dockers more easily.

**Comment by dave2wave** [comment]
Current code is:
```yaml
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker test build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          pull: true
          push: false
          load: true
          tags: ${{ env.DOCKER_TAGS }}

      - name: sanity check docker image
        run: |
          docker run --rm nosqlbench/nosqlbench:${{ env.RELEASE_VERSION_NUMERIC }} --version
```
