### ISSUE TITLE
Unable to load .yml workload files

### ISSUE THREAD

**Issue by szimmer1** [nosqlbench/nosqlbench#300]
**Describe the bug**
Unable to load .yml extension workload files. 

**To Reproduce**
1. Create a file `my-workload.yml` containing
```
bindings:
  alpha: Identity()
  beta: ToHashedUUID(); ToString()

statements:
  my-statement: |
    On cycle {alpha} beta is {beta}
```
2. Run with `java -jar nb.jar run driver=stdout workload=my-workload.yml cycles=10 format=assignments`, or `... workload=my-workload ...`
3. Observe the following fatal error
```
ERROR [main] ScenarioErrorHandler java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: error while reading file my-workload
```

**What was Expected**
Nosqlbench should have run 10 cycles and exited successfully. Note that renaming the file to `my-workload.yaml` gives the expected behavior.

**Additional context**
OS: Linux (Ubuntu), macOS
Version: 4.15.18
