### ISSUE TITLE
Add statement block sequence grouping with new param 'blockratio'

### ISSUE THREAD

**Issue by smccarthy788** [nosqlbench/nosqlbench#351]
**What is the ideal scenario for using this feature?**

This feature would allow users to specify the sequence and ratio of groups of statements (blocks), ideal when statements constitute a logic group.

**Is your feature request related to a problem? Please describe.**

The feature should enable users to run this example workload yaml and produce the statement sequence: `a,b,c,d,c,d,e,f`
```yaml
blocks:
  - params:
      blockratio: 1
    statements:
      - sA: a
      - sB: b
  - params:
      blockratio: 2
    statements:
      - sC: c
      - sD: d
  - params:
      blockratio: 1
    statements:
      - sE: e
      - sF: f
```

**Comment by jshook** [comment]
Since there is a distinct difference in behavior for how this should work vs other parameters, maybe we can make a clear distinction for any parameter that starts with `block`. As in, if a parameter starts with `block`, it is meant to apply to the block itself with all included operations kept as a unit.

Related, we should also clarify whether or not this is a valid construct due to parameter auto-structuring, as it would make for much more obvious examples and usage.
```
blocks:
  - blockratio: 1
    statements:
      - sA: a
      - sB: b
```
