### ISSUE TITLE
Consumer throwing a NullPointerException in v4.15.56

### ISSUE THREAD

**Issue by MMirelli** [nosqlbench/nosqlbench#363]
**Describe the bug**

The consumer in version 4.15.56 throws:

```
2021-10-06 06:38:45,496 [consumer-workload.yaml:001] ERROR: Error in core motor loop:java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.apache.pulsar.client.admin.Namespaces.getDeduplicationStatus(String)" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.apache.pulsar.client.admin.Namespaces.getDeduplicationStatus(String)" is null
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:16) ~[nb.jar:?]
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:52) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:44) ~[nb.jar:?]
        at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405) [nb.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.apache.pulsar.client.admin.Namespaces.getDeduplicationStatus(String)" is null
        at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.lambda$resolveMsgConsume$53(ReadyPulsarOp.java:462) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.ops.PulsarConsumerMapper.apply(PulsarConsumerMapper.java:59) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.ops.PulsarConsumerMapper.apply(PulsarConsumerMapper.java:28) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.apply(ReadyPulsarOp.java:66) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.apply(ReadyPulsarOp.java:27) ~[nb.jar:?]
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:41) ~[nb.jar:?]
        ... 4 more
```

**To Reproduce**

`start_workload yaml=consumer-workload.yaml cyclerate=100000`

`start_workload yaml=producer-workload.yaml cyclerate=50000`

start_workload:

```
java -jar nb.jar -v --report-graphite-to "${GRAPHITEHOSTPORT}" \
  --report-interval 30 \
  run \
  driver=pulsar \
  "config=config.properties" \
  web_url="${webServiceUrl:-https://${PULSAR_IP}:8443}" \
  service_url="${brokerServiceUrl:-pulsar+ssl://${PULSAR_IP}:6651}" \
  cycles='0..2147483647' \
  threads=1 \
  "${@}"
```

producer-workload.yaml:

```
description: async producer
params:
  topic_uri: persistent://public/ns/topic
  async_api: 'true'
blocks:
  - name: producer
    statements:
      - name: produce
        optype: ec2-msg-proc-send
        async_api: 'true'
        msg_value: "Wieghophuuwie5id9ied4oe2bae7geiSohzoo7harohf9Ea4Chi0thooDa2Zeceith3oacoh8ing0ohs3Eephaid2ahxikunuCh1que0phooP6iuRa8Thai0aemohsh0eQuaiphee0aehu6jequai8eixae2xau0agoo4saeQua7ro6chie4xuseicai7aivonohy6rai3Ohw7jiPaa0eequ9Kao4xeabaih9ohf5De8quaveig5hieB2tiecaiqu5ios1aek4faipae7uFiathashahw6feipae7fob7pieng4oongei7taalaiGeiy6aeGeiBu4obegeereetaaMuiciseehei0iugee3uip7Ailaixeis5Ge0Fabeepie7um8quiphoh9ushohPheeK5Leigheix0ahzailoer7ugh0shiqu3theeVimoh6Uwahm7Aiyae0Shaifeek5aiSemo2peiV9bi4Umezia5teex5eech8thei2aekee8oof2Geegh7waidoJ2thaogiexaehaixogaiw5vahr3kei0choi9chaefaputhu3IeziiNaik2thah8IeX7apak3ier3ish1yei9ziebuHeonahr6nahghooxee3eujaingopooge9Aivei0Ii7ieviv5xahc9eexong9aeveem4aigav0Be5iela0pheijeiJieM5xib8ohloen5oov3Aishaesufou8Dokeig7outhai3bacaeThae6goo0cahgue6iePhon8Eingac2zooseiphi9ush5jaiGheicaic6aetootood8idizahS7eeree2boh5eavu3Gie2ke3fosh7lieghuibeihongouXeejie0su7uoQu5ahwic4tang2bohtee3gae3tohQuie8ki1ReeGhiC2peiyaiGai3ighah4Ooh0thueb1ThaeRiemoh2ier1eyei4ahl9oopho5aih6mijohLatha1saek0aiBiet2sie3Uc0re0Taengah4nohshaeG1uD4guleeshe8ouyuQuoo4oa3eiMaeVi8phahXie5deipee2Ho0eenge8ahchah1lo2ig0meedaiBiep9Ie0ma8ookahs7quigie2mohlephaihiutahHeidi8Thoo5shaeGhoh8shei0shohyahmeewe3eiroo8naiDoh0ObeeWae3Jie4wahhei3iov9Waedileebeib5aifeedoo3aik8chailaij4awohdoo9aejae8ThootaeSaetooQu6yaihoPhiehaezeeQuaixei1ahbaShaegi8EimacechiequeetahcoocheQu8Ahkohthee5jaizeiphiicahphoon9iph3iifaicaz0gieshaic8ue7Cei2eamoov1Iefoo8zeNg9Roomu4ahp4uoceuCahf6EiJ6Kai2Shooy1paghu8aica1atheiLah7Vaid7wiem4too8apahjaghei1ko3uk0Eehe4ahlaiZ1ieghieth3aap7voo5wai4oongoimahhiebier7Zei6eic3baih2phoh1rei8pe2nahl1AengiepaYaphoh1ohngoov6wi7eich6aep3Oozoo4veesho2uquiu9aoLiod7ioveungeecooCiCaik7cuv0aeji4mooG1hiozeem6ushahp3eiQuumoo9chooz1CheoWiewiengahmaeFooyao9iepheneineimah8bimathee5eeseis0ooc5ya1kiabai4oTieThohgh3viez2tieyain9eiloo9Ahgho8aungey6ishooPhohloh8eegeed0ieshae6fie0aiJaePhewuR4Zohlie1ooph3niengio0ahpaifai1EehePieshae0geePhaikoh8ietiequu8iekuiph3phogeifaesai4aa4phaeziXi0aX8ooquaephahzeid9ohkahrilaim3tou7ge0gaikeePhoh4kaecahsee0aac0Aengool5Vie1ahza3oojohchohthogo6taeThohpa3ahun2gif2Jea9JahphePhaniekathailooyeegh5xahph1diek9oor7iFieCheeghaeLohtaiko8keil1oothuphohki8TohtohPh7son4cahgu1cu8amaof0aYeu0aeXiexoucukuazaeGhe2haighosahSh5SiGhaChiezoo3eophaeKiGeena8tos1Chiuveimohqu0dai1xaidieThee0ieGheibuz6aHa4Ahphee6cuuFah3pha9fohSiequohXei6thi1iepeC4ohhi5oofaen5Eechaixee2nigha9aeceePhooVeigaje5fohT2thoh5go5zei8oofeo2AluNahf9OhphaR3pefohz6jo3Ku2ughaigeehae3ahdeubeetaengeig6quoh8aibohbohrohTh8sae2Ahlae6emae2Haech3iePahXoh1Eu4leib9Ohngie6ex2Saiboothahnees0etung2veevie2iet1ohz9Yohyeipa7ohle3Eepaechoo0thuuWie7looNei2oopeengah7aiDaeSie7GiapooThee1viChem9phohphahrua9eithiXee0ees6foNo8hieba0sa2phohLaephieGh3ahZ1ophaechahyei9ohs0phoh9aenaomue2pa5ooNg2caha6Doo5eenohzaiwei7gae0mice0etai2eeseZ8nahwieSoolaey2yeiZee4aekiePae2Seezog2zie6modem8de2thosae3shonobohthooce3oopahw3vou5ingee4peijei1Ooyiinu3HowaiNgife1geejohqu8SeelieweePooHee9eeNuung8go4oobuoquahngoequingee4opohjeiNg9ahpohqu4oofaivae0Erie9zei4mohng6zaehieL7Pheboic6Paech2hai3Ahbo3oikew3vi5Uox0nooSheo7oGaiS3baevae9phulooyu0OomeuChiB3feeWeun1Ieghai6chaiz5Caeli2eic5chuweib0kohtaezae5Chahgh6ge4oopou8rohJ1heiquei2shohlau1eegh8ooyiochee1AetuY6eizeegoh9Iechoj2kee9geb4Peitah2ahFoong9kie1egho1aeM2ug9ieyaLeigheshiusoeSoquiev1Ied5nooGhingu3Eivetah5Aipohf3aipi5eithooga9aij7eeng7kee6caishoh7iiphies7AhSo9choo0yaezeiChohzeeyohsohc4quu9iequaenoo4shai8kePeechei1ei9neuph1na6oitiChaepo2geeng5Aghietheez8iTh3zeec9ailei6Yoh2duthee4fei7aduciedeeShoaha1ohy6xaew1vo1ueR9eiGohsenu3iesh3Oomai3Ieh3PheebahJ2phaoraibohngeeh1Vei1aiyoceetei7eep3iechee1veF5Upaeg4ahtiuJ4aila9Ieph7ethee8Gaxee8dei8neid4Kae4Sho2Ies7eebaiMieCere1aem5de9oKuvif0aeshai3ku8ou8biequieghaivahfohr0heiyupe9Goixa8OhmiDiqua5Nootai0Ooqu4Eugeicai5airoo8YithahHoh7kuliivu4Guphoop8aoNg6zei5etohyieNgo4eiWaiwaihohchuxiu5oirei3eeb1ahdiaFubaithiethaeQu9thoh6eefu4xohngahGhai7eewoh8aeRa4zeeshie2iopheemephahfe5eib4jialaeBiecheePheigooqu7Eboriech1ahziemie3ieThaefohvah7yaiJoodae5roozaePuj3ieciGhoob2yai9hie0Isheeg7Iengoongahfaceep4shahx4KeiJohJah2tohpiaSh4ahja1woh6being7yoz1aik9Ca4jaeCie1caijaiKie0aeth3iebie"
```

consumer-workload.yaml:

```
description: consumer
params:
  topic_uri: persistent://public/ns/topic
blocks:
  - name: consumer
    statements:
      - name: consume
        optype: ec2-msg-proc-consume
        subscription-name: nb
        subscription-type: Shared
```

config.properties

```
## check http://pulsar.apache.org/docs/en/client-libraries-java/
### Pulsar client related configurations - client.xxx
client.connectionTimeoutMs = 5000
client.useTls=true
client.tlsAllowInsecureConnection=true
client.tlsHostnameVerificationEnable=false
client.authPluginClassName=org.apache.pulsar.client.impl.auth.AuthenticationToken
consumer.subscriptionInitialPosition=Earliest
consumer.subscriptionName=nb
consumer.subscriptionType=Shared
consumer.receiverQueueSize=6000
consumer.maxTotalReceiverQueueSizeAcrossPartitions=200000
### error if no record is received in 300 seconds
consumer.timeout=300
producer.producerName =
producer.sendTimeoutMs =
producer.blockIfQueueFull=true
producer.maxPendingMessages=6000
producer.maxPendingMessagesAcrossPartitions=200000
client.authParams=file:///client/token-superuser/superuser.jwt
```

**What was Expected**

The consumer shouldn't throw an exception when consuming, which is what happens when using version 4.15.55 hinting a regression.
