### ISSUE TITLE
Custom timer metrics

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#49]
Some tests currently use the stride as an implicit bracketing around a group of statements for metrics, but the tests in question, this is complicated by the need to measure multiple brackets of statements.

If a statement parameter were added which can start and stop named metric timers, users could define the boundaries of metrics as they need. A proposed config format for this follows.

Phase 1:
This allows named metrics timers to be added with the existing APIs without requiring the more complete operators API, which will eventually subsume this functionality.

# start-local-timer
A statement parameter like this:
```
statements:
 - s1: a statement here
   param:
      start-local-timer: timer-named-foo
```
should start a named timer under the name provided, available in a thread-local cache, *before* the statement executes. 

# stop-local-timer

A statement parameter like this:
```
statements:
 - s2: another statement here
   param:
     stop-local-timer: timer-named-foo
```
should stop a named timer under the name provided, available in a thread-local cache, *after* the statement completes. If such named timer is not present, then an exception should be thrown.

For the initial phase of this implementation, it is ok to implement this per-activity type. The next phase should pull this up into the nosqlbench core APIs via a uniform mechanism.
