### ISSUE TITLE
Tag filtering errors/warning

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#596]
**Describe the bug**
Filtering by a specific tag. If we have a workload file structured as below:
```
description:
  ...

scenarios:
  ...

bindings:
  ...

blocks:
  - tags:
      phase: something_else
      type: write
    
  - tags:
      phase: main
      type: read
    params:
      ...
    statements:
      - statement1:
          SELECT * ...
        ratio: 1
        freeform: something
        tags:
          i1: i1
```
and when I invoke picking that specific tag by `tags=phase:main,type:read,i1:i1`, I am getting the following errors (although in `DEBUG` level):
```
2288 DEBUG [scenarios:001] CqlActivity  (☑,☑) filter(phase:main) tag(phase:main): matched pattern '^main$'
(☑,☑) filter(type:read) tag(type:read): matched pattern '^read$'
(☑,☐) filter(i1:i1) tag(): null tag value did not match '^i1$'
```

**To Reproduce**
See description above.

**What was Expected**
Statements satisfying the tag `i1 = i1` should be executed properly.

**Additional context**
Other context about the problem.
OS: macOS Monteray 12.1
environment: local
version info (`./nb --version` or `java -jar nb.jar --version`)
NB version used is `4.15.91`.

**Screenshots, if applicable**
n/a
