### ISSUE TITLE
Tolerance to spacing in named scenario definition

### ISSUE THREAD

**Issue by hemidactylus** [nosqlbench/nosqlbench#981]
*Note*: very minor issue!

When launching `nb5 run` from the shell, the tokenization from the shell itself makes it resistent to any number of spaces between directives:

```
nb5 run       driver=stdout        workload=so-and-so.yaml       cycles=10      tags=block:rampup
```

This, however, is not the case when defining a named scenario: there, only single spaces are allowed between directives, so that this is OK:

```
scenarios:
  default:
    schema:   run driver=cql tags==block:schema threads==1 cycles==UNDEF
    ...
```

while this isn't

```
scenarios:
  default:
    schema:   run driver=cql    tags==block:schema    threads==1      cycles==UNDEF
    ...
```

It would be nice to have this flexibility for a visually easier-to-maintain scenario definition (use case: I try to keep the parameters aligned between lines for easier reading).
